import React from "react";
import PostHero from "./postHero";

const Post = () => {
  return (
    <div className="max-w-220 w-full m-auto px-4">
      <PostHero
        title="A Deep Dive into the CSS font-size Property"
        publishedOn="2025-12-21"
      />
      <p className="text-lg font-medium text-amber-50">
        {" "}
        Note: This article was generated by ChatGPT, and is here purely to fill
        out this fake blog. Its essentially fancy Lorem Ipsum.
      </p>
      <p className="text-lg font-medium text-amber-50">
        Typography, the art of arranging type, is an essential ingredient in the
        recipe of impactful web design. A crucial player in this space is the
        CSS font-size property. This little piece of CSS syntax dictates how big
        or small the text on your website appears, shaping readability, user
        experience, and the emotional resonance of your site.
      </p>
      <p className="text-lg font-medium text-amber-50">
        Understanding how to wield the font-size property effectively can truly
        elevate your web design skills. But before we delve into the strategies
        and techniques, lets familiarize ourselves with the basics.
      </p>
      <p className="text-lg font-medium text-amber-50">
        The CSS font-size property controls the size of the text. It can accept
        various types of values, including length units (like px, em, rem),
        percentages, and keywords (like small, medium, large). For example, the
        syntax could be as simple as this:
      </p>{" "}
    </div>
  );
};

export default Post;
