import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_components/header";
import Footer from "./_components/footer";

import {cookies} from "next/headers";
import { COLOR_THEME_COOKIE_NAME } from "@/app/constants";

export type Theme = "light" | "dark";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const savedTheme = (await cookies()).get(
    COLOR_THEME_COOKIE_NAME
  );
  const theme = (savedTheme?.value as Theme) || "light";
  return (
    <html lang="en" className={`min-h-full min-w-full ${theme}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header initialTheme={theme}/>
        <main className="relative">
        {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
